version: "3.8"

services:
    dolidock:
        image: dolidock:latest
        volumes:
            - dolidock-data:/var/www/dolidock
        environment:
            DOLI_ADMIN_LOGIN: ${DOLI_ADMIN_LOGIN}
            DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD}
            DOLI_DB_TYPE: mysqli
            DOLI_DB_HOST: mysql
            DOLI_DB_HOST_PORT: 3306
            DOLI_DB_NAME: ${DOLI_DB_NAME}
            DOLI_URL_ROOT: 'http://0.0.0.0'
            DOLI_DB_USER: ${DOLI_DB_USER}
            DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "80:80"
    mysql:
        image: mysql:latest
        environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DOLI_DB_NAME}
        - MYSQL_USER=${DOLI_DB_USER}
        - MYSQL_PASSWORD=${DOLI_DB_PASSWORD}
        volumes:
        - mysql-data:/var/lib/mysql
        ports:
        - 3306:3306
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "500M"
volumes:
  dolidock-data:
  mysql-data: